FROM golang:1.16-stretch

SHELL ["/bin/bash", "-c"]
RUN apt update && apt-get install -y vim unzip git

# install protc
WORKDIR /protoc
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip
RUN unzip protoc-3.11.2-linux-x86_64.zip
RUN ln -s /protoc/bin/protoc /bin/protoc

# golang
WORKDIR /snsall
ENV GO111MODULE on
RUN go get -u github.com/golang/protobuf/protoc-gen-go \
  && go get -u github.com/pilu/fresh
RUN git config --global user.email "keigo2356@gmail.com" \
  && git config --global user.name "keigooba"

EXPOSE 8080

CMD ["fresh"]
