version: '3.7'
services:
  snsall:
    build:
      context: ./go-grpc/
      dockerfile: Dockerfile.dev
    container_name: "snsall"
    volumes:
      - ../:/snsall
    ports:
      - "8080:8080"
    tty: true
